name: fix code styling

on:
  push:
    branches:
      - master
      - '*.x'

permissions:
  contents: write

jobs:
  lint:
    uses: laravel/.github/.github/workflows/coding-standards.yml@main
    with:
      fix: ${{ github.ref_name == 'master' }}
